import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Halaman Utama</h1>

        <ul className={styles.menu}>
          <li><Link href={`/csr`}>CSR</Link></li>
          <li><Link href={`/ssr`}>SSR</Link></li>
          <li><Link href={`/isr`}>ISR</Link></li>
          <li><Link href={`/ssg`}>SSG</Link></li>
        </ul>
      </main>

    </div>
  )
}
